apiVersion: v1
kind: Namespace
metadata:
  name: dio
---
apiVersion: v1
kind: Secret
metadata:
  name: meuapp
  namespace: dio
type: Opaque
data:
  # valores de secrets, devem estar em base64
  # echo -n "123456" | base64 -w 0
  MYSQL_PASS: MTIzNDU2