apiVersion: v1
kind: Service
metadata:
  name: meuapp
  namespace: dio
spec:
  type: NodePort
  selector:
    app: meuapp
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30000
